### ISSUE TITLE
Safe Traps not trapping wild animals

### ISSUE THREAD

**Issue by ClarabelleS** [jaxxa/ED-SafeTraps#1]
Every time I install a Deadfall Trap and a wild animal enters the trap the debug log pops up and shows me this message. 
![debug log](https://cloud.githubusercontent.com/assets/20857403/17433524/733d1664-5b05-11e6-9d87-b0f659064779.PNG)
I already checked if other mods were an issue but the same message appears when I deactivate every other mod that isn't needed.
Is it possible to fix it?

**Comment by jaxxa** [comment]
Thanks for Reporting. This Should be fixed in the Latest version that I just put up (01.00.01). Please let me know if it isn't.
